version: "3"

services:
  hvault:
    container_name: vault
    image: vault:latest
    environment:
        - "VAULT_DEV_ROOT_TOKEN_ID=myroot"
        - "VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200"
        - "VAULT_ADDR=http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"